### ISSUE TITLE
Pull Requests / update vagrant-winnfsd 

### ISSUE THREAD

**Issue by marcharding** [winnfsd/winnfsd#20]
Does anyone still check the forks/latest pull request?

Quite a few bugs are squashed and vagrant-winnfsd would benefit a lot from the latest changes.

**Comment by GM-Alex** [comment]
Hey,

the problem currently for me is that I switched to Linux and I haven't setup a Windows pc to build the binary and so I'm not going to merge them without testing. Maybe someone want's to join the project?

**Comment by marcharding** [comment]
Hey Alexander,

since no one answered, feel free to add me. I'm no c/c++ expert, but i get along.

If you do, please also add me to vagrant-winnfsd and the rubygems account, i would like to keep everything in sync with each other.

**Comment by marcharding** [comment]
Thanks, i'll create a develop branch for both repositories and get going.
