### ISSUE TITLE
Problems with composer

### ISSUE THREAD

**Issue by hussainweb** [winnfsd/winnfsd#27]
This seems very similar to winnfsd/vagrant-winnfsd#22 but that issue spoke mostly about git and many reported it worked when using `--prefer-dist`. Also, that issue is closed and so I am opening a new one. I also believe that the issue is with the daemon and not the vagrant plugin.

This is the error I get when running `composer install`:

    Could not delete web/core/.nfs00000000000033b700000002

The relevant output with the error:

      - Installing drupal/core (8.2.x-dev 1274ea5)
    Reading /home/vagrant/.composer/cache/files/drupal/core/2a2aa3cc257cb9ecc6d30156f728e60ce4d02e06.zip from cache
        Loading from cache
        Extracting archive
    Executing command (CWD): unzip 'web/core/7b54013edc03201775f6d9cc2ce4af4f' -d '/var/www/bj8/vendor/composer/24996a58' && chmod -R u+w '/var/www/bj8/vendor/composer/24996a58'
        Failed to download drupal/core from dist: Could not delete web/core/.nfs00000000000033b700000002:
        Now trying to download from source
      - Installing drupal/core (8.2.x-dev 1274ea5)

      [RuntimeException]
      Could not delete web/core/.nfs00000000000033b700000002

At first, I thought this was with the recent update to 2.1.0. Then, I saw that there was an update to 2.1.1 and I tried that, which failed. Finally, I reverted the plugin to the old version with winnfsd 2.0 and I still get the above error.

If you need any more information, please let me know.

**Comment by marcharding** [comment]
Please try it with the exe linked here: https://github.com/winnfsd/winnfsd/issues/22#issuecomment-232504404.

Use TCP instead of UDP in your mount options (UDP fix will come later, maybe).

**Comment by amirbilu** [comment]
#22 solved the problem for me.

**Comment by hussainweb** [comment]
The file in #22 fixed the problem for me as well. I tried running `composer` twice and it worked both times (earlier, the failure was repeatable as well).

I forgot to set it to UDP before starting the machine and tried anyway. It worked without TCP enabled (unless it uses TCP by default). This is the block that defines the sync folder.

            machine_id.vm.synced_folder "#{folder['source']}", "#{folder['target']}",
              id: "#{i}",
              type: 'nfs',
              :nfs => { :mount_options => ["dmode=777","fmode=666"] }

This is the output from `mount` command:

    192.168.56.1:/D/Internet on /var/www type nfs (rw,relatime,vers=3,rsize=32768,wsize=32768,namlen=255,hard,nolock,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.56.1,mountvers=3,mountport=1058,mountproto=udp,local_lock=all,addr=192.168.56.1)

**Comment by hussainweb** [comment]
It seems that the fix is being discussed in #22. Should I close this or let this be open until the fix is in a release?

**Comment by marcharding** [comment]
Keep it open, i'll close it with the next release (hopefully in a few days).

**Comment by marcharding** [comment]
Fixed with 2.2.0.
