### ISSUE TITLE
Winnfsd & boot2docker

### ISSUE THREAD

**Issue by yannschepens** [winnfsd/winnfsd#3]
From : https://bitbucket.org/jankowfsky/winnfsd/issues/19/winnfsd-boot2docker

I'm trying to use WinNFSd with the vm boot2docker.
On Windows First I'm starting WinNFSd with this command line:
.\winnfsd.exe -log on C:\web
On the boot2docker vm: I start the nfs client by doing :
sudo /usr/local/etc/init.d/nfs-client start
Then
sudo mount -t nfs 10.0.0.1:/C/web /var/www -o vers=3
But I get this error: pmap_getmaps.c: rpc problem: RPC: Procedure unavailable mount: RPC: Unable to receive; errno = Connection refused mount: mounting 10.0.0.1:/C/web on /var/www failed: Bad file descriptor
Not sure what to do with this. Any help will be appreciated

**Comment by lmakarov** [comment]
Hi, I'm interested in winfsd as an option for https://github.com/blinkreaction/boot2docker-vagrant any progress. Could you, please, share any progress or timeline on fixing this issue?

**Comment by marcharding** [comment]
Hey if you're still interested this will be fixed in the next release. 

For testing purposes you can also try it with [this binary](https://github.com/winnfsd/winnfsd/files/389236/WinNFSd.zip) and report back.

**Comment by marcharding** [comment]
Fixed in 2.2.0.
