### ISSUE TITLE
Display application version in windows application property

### ISSUE THREAD

**Issue by magnetik** [winnfsd/winnfsd#31]
Currently, the application does not provide a way to see the application version in windows property (to check for the version for instance). 

I do not know if it's easy to add, but it might be a nice enhancement. 

Application property window:
![image](https://cloud.githubusercontent.com/assets/345029/18313655/04a96930-7510-11e6-863a-33ec826be8b7.png)

**Comment by marcharding** [comment]
I'd like to add this in the next version 👍

**Comment by marcharding** [comment]
Added in 2.3.0.
