### ISSUE TITLE
Memory leak fixes, canonical paths, 32bit handles

### ISSUE THREAD

**Issue by marcharding** [winnfsd/winnfsd#34]
> Hi all,
> 
> I made quite some changes to code (mostly memory fixes) but also quite some others. I am however not able to push this to repository. I am also not able to run the unit tests wit my version and also with older versions (test with writing files always seems to hang).
> 
> My changes are following:
> - memory leaks,
> - nfs file handle size (some nfs clients do not like 64 bit handles and do not allow to make the mount). This is controlled by option nfs3fhsize_32 ,
> - some nfs clients are requesting files in "path" path. path..\path. I guess they are testing if file is a file or a folder,
> - not all reparse points are links. winnfsd whould now support junction points correctly (eg.: you can mount to a folder),
> - case sensitivity I removed this
> 
> My changes are on top of 0e5fd89dc701550621b66ad95697f09269568b7d
> 
> Patch:
> [0001-Fixed-memory-leaks-added-nfs3fhsize_32-reparse-point.zip](https://github.com/winnfsd/winnfsd/files/493192/0001-Fixed-memory-leaks-added-nfs3fhsize_32-reparse-point.zip)
> 
> Executable:
> [WinNFSd.zip](https://github.com/winnfsd/winnfsd/files/493193/WinNFSd.zip)

see #15, further discussion in this issue.

**Comment by marcharding** [comment]
see https://github.com/winnfsd/winnfsd/tree/gregordoltar-patch for merged patch against current develop branch.

**Comment by marcharding** [comment]
I do not think case sensitivity should be removed

https://github.com/winnfsd/winnfsd/commit/494e719312dece60d2a04c7c77284c0c21f54704#diff-d5f03f6d54cca6f3ce516e43eb015e5dL354

see https://support.microsoft.com/en-us/kb/100625 for details about that.

As for all the other changes:

Seems to be good, tests do finish without problems https://ci.appveyor.com/project/MarcHarding/winnfsd-6y1xi/build/1.0.30

**Comment by marcharding** [comment]
There seem to be issues with this build, see https://github.com/winnfsd/winnfsd/issues/29#issuecomment-252094602

**Comment by andre-d** [comment]
This paths fix is important to the nfs client used in a particular application in our environment.   what is the status of this fix being mainlined, is there more work to be done to get it integrated?

**Comment by marcharding** [comment]
@andre-d some users reported crashes with these fixes (see comment above) and i did not find time to check it out, yet.

You can try the appveyor build youself https://ci.appveyor.com/project/MarcHarding/winnfsd-6y1xi/build/1.0.30 and see if there are any problems.

**Comment by Toilal** [comment]
Could you try this exe ? It includes #53 and #51 and fix and seems to fix memory related crashes.

[WinNFSd.zip](https://github.com/winnfsd/winnfsd/files/1351251/WinNFSd.zip)
