### ISSUE TITLE
2GB Ram Limit / 64x version

### ISSUE THREAD

**Issue by das-peter** [winnfsd/winnfsd#36]
Hi there,

I think the current version is limited to use 2 GB of memory due it's 32bit architecture.
When I use it the mounts become regularly unresponsive and when I check the task manager the winnfsd.exe is at about 2GB of RAM.
According to https://en.wikipedia.org/wiki/2_GB_limit we might can set a flag to increase allowed memory consumption: 
> 32-bit processes running on 64-bit Windows are also limited to 2 GB by default, but executables can have a "large address aware" flag set to increase this to 4 GB.

But it would be nicer if we'd have some sort of garbage collector and / or a 64x release.
Any ideas? ;)

I'll try to compile a 64x version but am not to confident I'll manage that because of my lacking knowledge.

**Comment by marcharding** [comment]
Hi, take a look at issue https://github.com/winnfsd/winnfsd/issues/29 where this behavior is discussed.

I think that merging the changes from @gregordoltar will probably migitate the issue quite a lot. Sadly there are some reports of winnfsd.exe crashing when the changes are applied. I'll come back to this in february...

**Comment by marcharding** [comment]
I'm closing this because the memory leaks are fixed (i think) so no need for this at the moment.
