### ISSUE TITLE
What is the correct format for mounting files?

### ISSUE THREAD

**Issue by ericclone** [winnfsd/winnfsd#37]
I just discovered winnfsd. I created a file called share.txt. In this file I have a few lines:
```
D:\work\project1 /nfs/project1
D:\personal\project2 /nfs/project2
...
```
But when I run WinNFSd.exe -pathFile share.txt, I get this error:

```
Path share.txt format is incorrect.
Please use a full path such as C:\work or \\?\C:\work
Can't open file share.txt.
```

What is the correct format for the file? Thanks.

**Comment by ericclone** [comment]
Ah ok I figured it out after reading the source code. It should be sourcepath>alias. My share.txt needs to be written as:

```
D:\work\project1>/nfs/project1
D:\personal\project2>/nfs/project2
...
Now everything works.
```

**Comment by marcharding** [comment]
When using an alias use >, though you can just omit the alias part, e.g.

```
D:\work\project1
D:\personal\project2 
```

results in the following shares

```
/D/work/project1
/D/personal/project2 
```

I'll update the documentation with the next release.
