### ISSUE TITLE
Win10, Android 5.0, Kodi: PORTMAP CALLIT - NOIMP

### ISSUE THREAD

**Issue by KreAch3R** [winnfsd/winnfsd#39]
Hello, I just found this great program and I'm trying to make it work on my Windows 10, using my tablet Pixi3 (10) (Android Lollipop 5.0) and Kodi 16.1 (from playstore). Both are connected to the same network (PC with Ethernet and Tablet with WiFi).

My Server (Windows 10) is using the **192.168.1.6** IP address. I am using the latest .exe, although I did try with the rest that I found in the open issues.

**NOTICE**: If I don't use the *-addr* argument, the program prints that it listens to "0.0.0.0".

```
D:\Downloads>WinNFSd.exe -addr 192.168.1.6 D:\Videos /Videos
=====================================================
WinNFSd 2.3.1 [ff041cb]
Network File System server for Windows
Copyright (C) 2005 Ming-Yang Kao
Edited in 2011 by ZeWaren
Edited in 2013 by Alexander Schneider (Jankowfsky AG)
Edited in 2014 2015 by Yann Schepens
Edited in 2016 by Peter Philipp (Cando Image GmbH), Marc Harding
=====================================================
Path #1 is: D:\Videos, path alias is: /Videos
Portmap daemon started
NFS daemon started
Mount daemon started
Listening on 192.168.1.6
Type 'help' to see help

PORTMAP CALLIT - NOIMP
PORTMAP CALLIT - NOIMP
PORTMAP CALLIT - NOIMP
```

I tried to search for a solution, I came across #28 but that problem is already supposed to be fixed in the version I tried.

Let me know of any debugging I can do to help.

**Comment by marcharding** [comment]
Did you use the discover function in Kodi to search for shares on 192.168.1.6? This does not work yet.

When you directly add the share, e.g. 192.168.1.6/Videos it should work. 

Binding to 0.0.0.0 just means winnfsd is listening on all  devices.

**Comment by KreAch3R** [comment]
@marcharding yes, that was exactly what I was trying. I had no idea the function would be different. It indeed works!

Now time to make it into a service. Thank you for this. :)
