### ISSUE TITLE
Include a link to the latest binary

### ISSUE THREAD

**Issue by jxmallett** [winnfsd/winnfsd#43]
Thanks for your work on this.

I was thinking I'd have to build this from source but I found your AppVeyor project. It would be great to add this link to the readme file.

The latest binary can be found here:
https://ci.appveyor.com/project/MarcHarding/winnfsd-6y1xi/build/artifacts

**Comment by marcharding** [comment]
You can also find the binares under releases https://github.com/winnfsd/winnfsd/releases (all officially relased versions) .

**Comment by jxmallett** [comment]
Ha, not sure how I missed that. Thanks!
