### ISSUE TITLE
Execute flag/permission can not be set

### ISSUE THREAD

**Issue by planesweep** [winnfsd/winnfsd#47]
Hello,

I am not able to set the execute flag/permission of files with

- sudo chmod +x or
- via mount -o 'vers=3,nolock,udp,exec' 

Any suggestions?

Used version https://github.com/winnfsd/winnfsd/releases/tag/2.3.1

**Comment by Toilal** [comment]
on windows host, it's not possible to store those permission.

It would actually require to implement an additional store to read/write those permissions (=> metadata database).

**Comment by marcharding** [comment]
What @Toilal is correct (there are some ntfs attributes which could me used, but it is not worth it), this will not be implemented, sorry
