### ISSUE TITLE
Bad allocation

### ISSUE THREAD

**Issue by Toilal** [winnfsd/winnfsd#52]
After setting up visual studio debuger and enhanced error message handling with #51, I can now help to diagnose crashes we experience in my dev team.

It throws an exception with message `Bad allocation` after a while.

When I debug, it fails to create a new char array in [FileTree GetNodeFullPath](https://github.com/winnfsd/winnfsd/blob/4e412a75494a29b71d10b3be2b90460e96e3828c/src/FileTree.cpp#L285) method.

**Comment by Toilal** [comment]
So this one in fixed with the merge, thanks.

**Comment by marcharding** [comment]
I also published the new gem. Thanks for your work on this 🎉
