### ISSUE TITLE
Can't start winnfsd.exe on Windows 10 Pro

### ISSUE THREAD

**Issue by ArminVieweg** [winnfsd/winnfsd#55]
Hey,
I've got two PCs using Windows 10 Professional. One desktop, one laptop.
On my desktop, everything works fine.

On my brand new laptop not. When I am using a Vagrantfile which works on Desktop, on my laptop the process hangs up, when `==> default: Mounting NFS shared folders...`

When I check processes, there is no NFS service, on laptop. On Desktop (where it works) there is such process.

When I try to start winnfsd.exe manually (directly or with nfsservice.bat file) an error occures and the process get terminated. Error in windows error logs:

```
Name der fehlerhaften Anwendung: winnfsd.exe, Version: 2.3.1.0, Zeitstempel: 0x58000198
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc0000005
Fehleroffset: 0x00015ae0
ID des fehlerhaften Prozesses: 0x3454
Startzeit der fehlerhaften Anwendung: 0x01d33d0e39956c56
Pfad der fehlerhaften Anwendung: C:\Users\Armin\.vagrant.d\gems\2.3.4\gems\vagrant-winnfsd-1.3.1\bin\winnfsd.exe
Pfad des fehlerhaften Moduls: unknown
Berichtskennung: 8d0c7ef3-a881-4c51-8ddc-7b73ce391ea9
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

After the error entry, there is also a info entry:
```
Fehlerbucket 116455397201, Typ 5
Ereignisname: BEX
Antwort: Nicht verfügbar
CAB-Datei-ID: 0

Problemsignatur:
P1: winnfsd.exe
P2: 2.3.1.0
P3: 58000198
P4: StackHash_b4ee
P5: 0.0.0.0
P6: 00000000
P7: PCH_87
P8: c0000005
P9: 00000008
P10: 
```

Probably there is just a wrong setting, or something like this... But I have absolutely no idea. I've also reinstalled the vagrant plugin, disabled firewall entirely... It is just not working on my laptop, while it works like charm on my Desktop.

Thanks in advance.

**Comment by jamesmacwhite** [comment]
@ArminVieweg I recently had issues with `vagrant up` hanging on "Mounting NFS shared folders" too (when it had worked fine for months). Also Windows 10 Professional, on my Dell XPS 9550.

In the end, I ended up updating Vagrant and VirtualBox to the latest versions and then made sure guest tools were installed in the virtual machine and matched the version of VirtualBox. Then rebooted.

After doing that the nfs mount no longer hung. It was bizarre though, as nothing had changed.

Thought, I'm not sure if the network connectivity at the time may of been a factor, as it looked the corporate network I was on was interfering with bridged network interface IP range and localhost requests (some proxy server).

**Comment by ArminVieweg** [comment]
I've got a brand new Thinkpad P51s. And it is less than two weeks ago, that I've set up the laptop entierly. So all versions are up2date.

When I execute winnfsd.exe at the Desktop PC, I'll get the help text of winnfsd. On my laptop a windows error occures (which try to fix... blah blah).

I also don't use VPN, but I'll check the network settings.

Are there any libraries required to be installed? Maybe some kind of dll is missing... (just guessing)

**Comment by ArminVieweg** [comment]
Okay. This is weird. Now it works. But I'm at home. Not at work, where I've had the issues. Can the network influence this? Both are wifis with DHCP.

**Comment by jamesmacwhite** [comment]
Yes potentially. Network is important.

Do you have set in your Vagrantfile?

```
config.vm.network "private_network", type: "dhcp"
```

**Comment by ArminVieweg** [comment]
> config.vm.network "private_network", type: "dhcp"

Yes.

**Comment by jamesmacwhite** [comment]
If it worked at home, but not in another location, then as I was saying before network is a likely area.

At work, if you have some form of proxy server interfering potentially.

**Comment by ArminVieweg** [comment]
I have absolutely no idea... but now it works. Also at work. I did not change anything! If the issue occures again I start a new topic. Thanks!
