### ISSUE TITLE
Unable to see or read hidden files in Windows 10 Fall Creator's Update

### ISSUE THREAD

**Issue by cbj4074** [winnfsd/winnfsd#56]
`WinNFSd 2.3.1 [ff041cb]`

Has anybody else tried `winnfsd.exe` on Windows 10 Fall Creator's Update?

WinNFSd was working great for me prior to, but after installing this update, I notice that hidden files (those whose name begins with a dot `.`) cannot be accessed; they don't appear in directory listings and despite being able to `stat`, any attempt to open them results in read errors.

The stat output for a hidden text file is

```
  File: '.env'
  Size: 581             Blocks: 2          IO Block: 32768  regular file
Device: 2bh/43d Inode: 0           Links: 1
Access: (0777/-rwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2017-11-05 16:15:51.000000000 +0000
Modify: 2017-11-05 16:20:29.000000000 +0000
Change: 2017-11-05 16:20:29.000000000 +0000
 Birth: -
```

but when I try to open it in Vim, for example, I see `".env" [READ ERRORS] 0L, 0C`, and when I close it without saving, `E72: Close error on swap file`.

For example, this directory contains a `.env` file (and, of course, I'm able to see it on the Windows side), yet it doesn't appear, even with the `-a` flag:

```
vagrant@homestead:~/Code/project$ ls -lah
total 186K
drwxrwxrwx 1 root root 8.0K Nov  7 12:24 .
drwxrwxrwx 1 root root 4.0K Nov  5 15:43 app
-rwxrwxrwx 1 root root 1.7K Nov  5 15:43 artisan
drwxrwxrwx 1 root root    0 Nov  5 15:43 bootstrap
-rwxrwxrwx 1 root root 5.5K Nov  5 15:43 CHANGELOG.md
-rwxrwxrwx 1 root root 1.5K Nov  5 15:43 composer.json
-rwxrwxrwx 1 root root 136K Nov  5 16:31 composer.lock
drwxrwxrwx 1 root root 4.0K Nov  5 15:43 config
drwxrwxrwx 1 root root 4.0K Nov  5 15:43 database
-rwxrwxrwx 1 root root 1.2K Nov  5 15:43 package.json
-rwxrwxrwx 1 root root 1.1K Nov  5 15:43 phpunit.xml
drwxrwxrwx 1 root root 4.0K Nov  5 15:43 public
-rwxrwxrwx 1 root root 3.6K Nov  5 15:43 readme.md
drwxrwxrwx 1 root root    0 Nov  5 15:43 resources
drwxrwxrwx 1 root root    0 Nov  5 15:43 routes
-rwxrwxrwx 1 root root  584 Nov  5 15:43 server.php
drwxrwxrwx 1 root root    0 Nov  5 15:43 storage
drwxrwxrwx 1 root root    0 Nov  5 15:43 tests
drwxrwxrwx 1 root root 8.0K Nov  5 16:31 vendor
-rwxrwxrwx 1 root root  564 Nov  5 15:43 webpack.mix.js
```

If I try to access the `.env` file:

```
vagrant@homestead:~/Code/project$ touch .env
touch: setting times of '.env': Input/output error
```

The directory also has a `.git` subdirectory, which I'm able to access, despite not being able to see it:

```
vagrant@homestead:~/Code/project$ cd .git
vagrant@homestead:~/Code/project/.git$ ls -lah
total 32K
drwxrwxrwx 1 root root 4.0K Nov  5 18:13 .
drwxrwxrwx 1 root root 8.0K Nov  7 12:24 ..
-rwxrwxrwx 1 root root  496 Nov  5 16:34 config
-rwxrwxrwx 1 root root   73 Nov  5 15:43 description
-rwxrwxrwx 1 root root    0 Nov  5 16:34 FETCH_HEAD
-rwxrwxrwx 1 root root   23 Nov  5 15:43 HEAD
drwxrwxrwx 1 root root 4.0K Nov  5 15:43 hooks
-rwxrwxrwx 1 root root 8.7K Nov  5 15:43 index
drwxrwxrwx 1 root root    0 Nov  5 15:43 info
drwxrwxrwx 1 root root    0 Nov  5 15:43 logs
drwxrwxrwx 1 root root    0 Nov  5 15:43 objects
-rwxrwxrwx 1 root root 4.6K Nov  5 16:32 packed-refs
drwxrwxrwx 1 root root    0 Nov  5 15:43 refs
```

I'm not 100% certain that the Creator's Update caused this, but I will work to establish that, which may take some time.

**Comment by marcharding** [comment]
No issues here, windows 10 fall creators update, winnfsd 2.3.1/2.4.0 (no problems with both versions).

**Comment by cbj4074** [comment]
Thanks, @marcharding ! Glad to know that it should still work on Fall Creator's Update.

Any idea what else might be causing this? Never seen it before?

Thanks again for the reply. Feel free to close this if you don't recognize this issue, and I'll re-open it when I can reproduce it on more than one system.

**Comment by cbj4074** [comment]
I just upgraded to `vagrant-winnfsd-1.4.0` via `vagrant plugin update` and the problem is gone! The cause seems to be academic at this point; let's close it!
