### ISSUE TITLE
Very slow writing performance, compared to haneWin NFS Server for instance.

### ISSUE THREAD

**Issue by Yivan** [winnfsd/winnfsd#59]
Thanks for this nice free alternative for making a nfs server on Windows. So few exists!

I wanted to use Winnfsd and replace haneWin NFS Server which is not open source with Winnfsd. So I proceeded to benchmark read and write speed to check all is ok with Winnfsd. It found that read speed is same, but Winnfsd write speed is around 10x slower than haneWIN NFS Server.

Mounts have exactly the same options (verified with the `mount `command which list mounted directory and their repective options) and tested one after the other (so only one NFS server runned at a time).

Is it normal (this is the espected speed of Winnfsd) or should it be as fast than haneWin NFS Server ?

---

To test:

- Install haneWin NFS Server (https://www.hanewin.net/nfs-e.htm) and create an export
- Install Winnfsd and create the same export
- Create a Linux VM using Virtualbox

1- Start Winnfsd, mount the export on the VM, change directory to the mounted folder and run following commands:

```
dd if=/dev/zero of=./output bs=8k count=10k; rm -f ./output
```
Write speed: around 5 MB/s

```
dd if=/dev/zero of=./output bs=8k count=10k
dd if=./output of=/dev/null bs=8k
```
Read speed: around 33 MB/s (first run, if command is re-run around 5 Gb/s because NFS caching. Cache can be reset with `echo 3 | sudo tee /proc/sys/vm/drop_caches`)

2- umount the export, shutdown Winnfsd, start haneWin NFS Server (and SunMapRPC), in the VM mount the export and run following commands:

`dd if=/dev/zero of=./output bs=8k count=10k; rm -f ./output`
Write speed: around 50 MB/s, so 10 times faster than Winnfsd

For read speed this is the same than Winnfsd.

**Comment by Yivan** [comment]
I should just add used option used in the mount are: `rw,hard,nolock`, no option is configured on the export.

**Comment by cbj4074** [comment]
@Yivan Did you run your tests with both `tcp` and `udp` in the mount options? If not, can you re-run them with `udp` specified?

**Comment by Yivan** [comment]
@cbj4074 Thanks for looking for it.

My test was with TCP.
I just tested winnfsd by mounting it with option proto=udp, and write speed is the same (around 5 MB/s).
(i checked with `mount `command that my mount is in UDP, and it was)

**Comment by cbj4074** [comment]
@Yivan Great; thank you for testing with both protocols. I don't have an explanation or a solution for you, unfortunately, but I'm sure that your efforts will assist the developers in assessing the situation.

**Comment by marcharding** [comment]
`83886080 bytes (84 MB) copied, 0.309554 s, 271 MB/s`

`nfs (rw,vers=3,udp,vers=3,tcp,addr=192.168.56.1)`

There seems to be something wrong with your machine and/or mount. Maybe some antivir?

If you're using virutalbox, try the virtio network interface.

**Comment by Yivan** [comment]
Thanks marcharding.
But changing to virtio is the same speed.

I just tried on a totally different computer (Windows 7SP1 instead of Windows 10, différent firewall/antivirus, but they are desactivated during my tests).

On this other setup (so W7 SP1), i cannot test because WinFSD don't work... Mounting is ok, i can `cd` in the mount, but when i run:
`dd if=/dev/zero of=./output bs=8k count=10k; rm -f ./output`
it is endless... cpu is max (1 thread), and i have to close the VM.
:(

@marcharding how do you achieve such speed ? What is your setup and how do you run Winnfsd ?
Currently, my settup is pretty common: windows with virualbox (uptodate) and boot2docker (uptodate).

My `C:\winnfsd\export.txt` file contain:
`C:\MyFolder > /MyFolder`
And i run winfsd in command elvated with administrator right by running a .bat file containing:
`WinNFSd.exe -pathFile C:\winnfsd\export.txt`
I mount the share on the docker host (so boot2docker on virtualbox) with:
`sudo mount -t nfs -o rw,hard,nolock 192.168.99.1:/ServeurLocal /mnt/ServeurLocal`
(192.168.99.1 is my windows host IP see from the host-only adapter. I don't use the NAT adapter IP 10.0.2.2 because i find it to be more slower with HaneWin NFS...)

So my environnement is pretty reproductible and i confirm i have this speed problem on 2 totally different computer.
Has Winnfsd some problem with boot2docker ?

**Comment by marcharding** [comment]
Are you using the latest version (2.4.0)?

**Comment by Yivan** [comment]
Yes the last 2.0.4

**Comment by Yivan** [comment]
@marcharding 
Any update on this ?

Maybe you could try to install HaneWin on your side and benchmark it against winnfsd
https://www.hanewin.net/nfs-e.htm
There is a 30 days free trial if i remember. Or you can buy it it's not so much expensive.

If you get this `83886080 bytes (84 MB) copied, 0.309554 s, 271 MB/s` maybe your setup has better ssd/config power than me and with hanewin the result will be like me better than what you get with winnfsd.
It will show than winnfsd could be optimised or has some locks which slow it him.

Any people here made some benchmark againt winnfsd / hanewin to see if winnfsd is a real open-source alternative with same performance ?  Could you post them here please ?

Thanks a lot ! I would love to see winnfsd perform as well, it will make happy all vagrant/virtualbox/docker user on windows : ))

**Comment by elebeaup** [comment]
I have the same issue. I found that write speed is very slow compared to HaneWin NFS.

**WinNFS**
```
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 2.95943 s, 34.6 MB/s
```

**HaneWin NFS**
```
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 0.486866 s, 210 MB/s
```

For information, I am trying the benchmark with Docker For Windows.

**Comment by elebeaup** [comment]
I have resolved the issue by disabling the logging.

```
100000+0 records in
100000+0 records out
102400000 bytes (102 MB, 98 MiB) copied, 0.498466 s, 205 MB/s
```

@marcharding Thanks for your work.

**Comment by cbj4074** [comment]
That's interesting @elebeaup , thanks for the follow-up.

@Yivan Do you happen to have logging enabled? I know it's been a while since you last posted in this thread... curious if you've made any discoveries since then.

**Comment by Yivan** [comment]
@cbj4074 I didn't edit any loggin option. If it is enabled by defaut, it was enabled so ; ) If not it was not enabled.

Sorry, no new discovery for now. I switched to the native Samba used by Docker for Windows.

**Comment by cbj4074** [comment]
@Yivan Thanks for the speedy follow-up!

In that case, it may be prudent to close the issue if and until somebody else reports the same and confirms that logging is disabled.

@elebeaup 's benchmarks with 210 MB/s for HaneWin and 205 MB/s for WinNFSd imply that there isn't a significant difference when logging is disabled.

Thanks again!

**Comment by Yivan** [comment]
@cbj4074 Yes sure, I close the issue. If i test again i will try to check if log is enabled or not and post result here.
Thanks.

**Comment by elebeaup** [comment]
@cbj4074 @Yivan Logging is enabled by default.

**Comment by cbj4074** [comment]
Hmm, this raises two questions for me:

1. Should logging be disabled by default, instead?
2. Is logging enabled by default for the Vagrant plugin, too? The docs imply that it is not, but it seems prudent to confirm.

I'll do some testing with the Vagrant plugin in an effort to confirm the default behavior.
