### ISSUE TITLE
Portmap daemon starts failed

### ISSUE THREAD

**Issue by fartusco** [winnfsd/winnfsd#63]
Hello,

I have been running WinNFSd for some time now and it has worked correctly so far.

However, WinNFSd has been out of operation for a few days now, coinciding with the installation of some Windows 10 updates.

On the command line I run WinNFSd:

C:\Conex\nfsServer\bin>WinNFSd -pathFile "c:\Conex\nfsServer\exports.txt"

Here is the log for winnfsd.exe:

WinNFSd 2.4.0 [5f7f224]
Network File System server for Windows
Copyright (C) 2005 Ming-Yang Kao
Edited in 2011 by ZeWaren
Edited in 2013 by Alexander Schneider (Jankowfsky AG)
Edited in 2014 2015 by Yann Schepens
Edited in 2016 by Peter Philipp (Cando Image GmbH), Marc Harding
=====================================================
Path #1 is: C:\Conex\auto\m3a, path alias is: /srv/m3a
Path #2 is: C:\Conex\auto\m2a, path alias is: /srv/m2a
Portmap daemon starts failed.

Can you help me?

Thank you very much.

**Comment by Pascal66** [comment]
Same problem after restarted windows.
Working well before restart !?
[Resolved] i've a hidden nfs deamon running

**Comment by fartusco** [comment]
How can I check if I have a hidden nfs daemon running?

Thanks.

**Comment by fartusco** [comment]
Okay. Solved.

There was indeed a hidden nfs demon running.

Thank you very much.

**Comment by cbj4074** [comment]
@fartusco It might be useful to others if you explain how you determined as much. 👍

And what was the other daemon that was running? Something you installed and forgot about? Some other piece of legitimate software? Malware?

**Comment by fartusco** [comment]
You're right, cbj4074.

The other NFS daemon that was running was the cygwin NFS server. This is the solution I intend to replace with WinNFSd. I didn't realize that to do some tests I had to re-install it and it was still running.

As soon as I stopped and uninstalled it, WinNFSd returned to normal operation.

Thank you very much for your help.

A greeting.
