### ISSUE TITLE
multiple disk ?

### ISSUE THREAD

**Issue by GeorgeSands** [winnfsd/winnfsd#80]
Is it possible to mount multiple disks like C: / D: / E: / and how to do that ? 

I try the multiple paths metod by export but this do not work ...

**Comment by MMaurente** [comment]
I have the same doubt.

**Comment by Buba5473** [comment]
From KODI's forum:

"With the lack of SMB support on Kodi for XBox1 a good alternative is NFS, but it's not supported natively on most versions of win.
There are some easier methods to do that (haneWIN's nfs server) but not free (afaik).
Here's a way to add NFS service capabilities on win using the FOSS WinNFSd.

1. Download WinNFSd.exe latest version from here (2.4.0 as of now)
2. Place it in a new folder. I'm gonna use C:\winnfsd for this guide.
3. Inside that folder create a text document, name it exports.txt, open it and paste inside the paths you'd like to share (eg F:\Videos). One path per line, and start from the second line - leave first line blank! (I don't know why but in my case the path I put in the first line didn't get shared).
4. Create another text document in the same folder, name it nfsservice.bat, and paste in it: winnfsd.exe -id 0 0 -log off -pathFile "C:\winnfsd\exports.txt" and save it.
5. Right-click on that file, Send to -> Desktop (create shortcut). 
6. Move shortcut to windows's startup folder (C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup)

That's it, run nfsservice.bat or restart (the service will start on every boot).

- Optional, add your windows pc's ip on (client) Kodi's file manager as an NFS source: Settiings/File Manager/Add source/Browse/Add network location/Protocol: NFS, Server address: IP of win pc/OK/give-a-name/OK.
Now you won't have to do it again and again when you're adding media sources, the server will be listed and you'll just choose your desired path from it. "

**Comment by bandit001** [comment]
I have the same doubt.
